#define RADIO_AX5043 
#define USE_LCD
//#define USE_DBGLINK
//#define USE_COM0
//#define DEBUGMSG 
#define MCU_SLEEP
#define BASICTESTS 11
#define BASICTESTS_TXPATTERN 0x55555555
#define BERDIGITS 4
#define WTIMER0_CLKSRC CLKSRC_LPOSC
#define WTIMER0_PRESCALER 0x01
