/* Warning: This file is automatically generated by AX-RadioLAB.
	Manual changes are overwritten! */

#include "../COMMON/axradio.h"


const struct axradio_address __code remoteaddr = {
	{ 0x33, 0x34, 0x00, 0x00}
};
const struct axradio_address_mask __code localaddr = {
	{ 0x32, 0x34, 0x00, 0x00},
	{ 0x00, 0x00, 0x00, 0x00}
};


const uint8_t __code framing_insert_counter = 0;
const uint8_t __code framing_counter_pos = 15;


const uint8_t __code demo_packet[] =  { 0xA6, 0x82, 0xA8, 0x40, 0x40, 0x40, 0x60, 0x96, 0x94, 0x6E, 0xA6, 0xAA, 0x40, 0x61, 0x03, 0x00, 0x48, 0x69 };


const uint16_t __code lpxosc_settlingtime = 3000;
