/* Warning: This file is automatically generated by AX-RadioLAB.
	Manual changes are overwritten! */


#include "libmftypes.h"

// Spec: Internal 800MHz...1050MHz External 140MHz...525MHz

#define FREQINC    0x55555
#define FREQSTART  700
#define FREQEND    1150
const uint32_t __code freqinc = FREQINC;
const uint32_t __code freqincmhz = 0x55555;
const uint32_t __code freqstart = FREQSTART * FREQINC;
const uint32_t __code freqend = FREQEND * FREQINC;
#undef FREQINC
#undef FREQSTART
#undef FREQEND
